In [2]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 2s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6982249 ,  0.9921893 , -0.39700007, -0.66950065, -0.15435524,
        -0.0885731 , -0.06051862,  0.12622017, -0.1995905 ,  0.5826597 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.04590552, 0.24888712, 0.06204191, 0.04724324, 0.0790796 ,
        0.08445654, 0.08685947, 0.10469279, 0.07558211, 0.16525173]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.471518

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2928 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1448 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1092 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0880 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0756 - accuracy: 0.9758


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0724 - accuracy: 0.9779


[0.0724005401134491, 0.9779000282287598]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.83660224e-08, 4.36957892e-09, 5.46524916e-06, 3.37528727e-05,
        2.30156762e-11, 2.12398717e-07, 1.12390776e-13, 9.99958873e-01,
        7.85888048e-08, 1.61488072e-06],
       [2.19110959e-07, 7.60390365e-04, 9.98882115e-01, 3.49600654e-04,
        6.56581454e-16, 2.16417743e-06, 9.25329573e-07, 2.07192614e-11,
        4.57451688e-06, 1.41101730e-13],
       [1.63736090e-07, 9.99448597e-01, 1.01571917e-04, 2.15626119e-06,
        9.38219637e-06, 7.21637753e-06, 2.01725452e-05, 2.90847645e-04,
        1.19600183e-04, 2.49574157e-07],
       [9.98566926e-01, 7.35276353e-06, 2.18007845e-04, 2.21482969e-06,
        1.91760265e-07, 1.14762814e-04, 2.01825824e-05, 1.06185279e-03,
        2.27986064e-07, 8.17656110e-06],
       [4.13352745e-06, 5.24162367e-08, 4.13432826e-06, 2.77249743e-08,
        9.98003185e-01, 3.97148779e-06, 2.64794253e-05, 4.47900762e-04,
        1.59816750e-06, 1.50850054e-03]], dtype=float32)>